# Generated by Django 3.2.9 on 2021-11-01 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('f', 'Front-end'), ('b', 'Back-end'), ('o', 'Other')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timespan', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('institute', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True, max_length=2000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timespan', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('institute', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True, max_length=2000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('fullname', models.CharField(max_length=200)),
                ('career', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('Gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('linkedin', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter_url', models.URLField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('facebook_url', models.URLField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram_url', models.URLField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=200)),
                ('percent', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='pfolio.category')),
            ],
        ),
    ]
